#!/bin/bash

TWO=2
if [ "$#" -ne "$TWO" ]
then
    echo "Usage: `basename $0` [directory] [size in MB]"
    exit 0
fi

PREDICAT=/tmp/filtergen.$$
DIR="$1"
SIZE="$2"

echo " #!/bin/bash
SIZEF=\`stat -c %s \"\$1\"\`
GOODSIZE=$SIZE
(( GOODSIZE = (GOODSIZE)*1024*1024 ))
if [ \$SIZEF -gt \$GOODSIZE ]
then
    exit 0
fi
exit 1 " > "$PREDICAT"

chmod +x "$PREDICAT"

#find "$DIR" -print0 | ./filter -z -- "$PREDICAT"
find "$DIR" | ./filter -nb 1024 -- "$PREDICAT"

rm "$PREDICAT"
