#!/bin/bash

TWO=2
if [ "$#" -ne "$TWO" ]
then
    echo "Usage: `basename $0` [directory] [size in MB]"
    exit 0
fi

PREDICAT=/tmp/findGoodSizeFilesPredicat
DIR=$1
SIZE=$2
echo " #!/bin/bash
SIZEF=\`stat -c %s "\$1"\`
(( MSIZE = (SIZEF)/1024/1024 ))
if [ "\$MSIZE" -gt "$SIZE" ]
then
    exit 0
fi
exit 1 " > "$PREDICAT"

chmod +x "$PREDICAT"

find "$DIR" -print0 | ./filter -z -- "$PREDICAT"

rm "$PREDICAT"
