#!/bin/bash

MIN_ARGS=2
E_BAD_ARGS=65
CURR_OUTPUT="Current output -----------------------"
DELIMITER="--------------------------------------"
DIFF="Difference with the previous output --"

if [ "$#" -lt "$MIN_ARGS" ]
then
    echo -e "Usage: `basename $0` [time in seconds] [command]"
    exit $E_BAD_ARGS
fi

time_for_wait="$1"
shift

STATE_FIRST=/tmp/watchthis1.84
STATE_SECOND=/tmp/watchthis2.84

echo "" > "$STATE_FIRST"
echo "" > "$STATE_SECOND"

trap 'rm -f $STATE_FIRST $STATE_SECOND; echo -ne "\n"; exit 130' 2

while [ 1 ]
do
    echo "$("$@")" > "$STATE_FIRST"
    echo "$CURR_OUTPUT"
    cat "$STATE_FIRST"
    echo "$DELIMITER"
    df=$(diff -u "$STATE_FIRST" "$STATE_SECOND")
    if [ "$df" ]
    then
        echo "$DIFF"
        echo "$df"
        echo "$DELIMITER"
    fi
    cat "$STATE_FIRST" > "$STATE_SECOND"
    sleep $time_for_wait
done

#rm -f $STATE_FIRST $STATE_SECOND #redundant line