#!/bin/bash

ZERO=0
E_NOARGS=65
E_NOPROCESS=2

if [ "$#" -eq "$ZERO" ]
then
    echo -e "Usage: `basename $0` [time in seconds] [command]"
    exit $E_NOPROCESS
fi

time_for_wait="$1"
shift
process=$("$@")
echo "$process"
echo "#########"
sleep "$time_for_wait"
process=$("$@")
echo "$process"
