#!/bin/bash

MIN_ARGS=2
E_BAD_ARGS=65

if [ "$#" -lt "$MIN_ARGS" ]
then
    echo -e "Usage: `basename $0` [time in seconds] [command]"
    exit $E_BAD_ARGS
fi

time_for_wait="$1"
shift

STATE_FIRST=/tmp/watchthis1.$$
STATE_SECOND=/tmp/watchthis2.$$

process=$("$@")
echo "$process" > $STATE_FIRST
sleep "$time_for_wait"
process=$("$@")
echo "$process" > $STATE_SECOND

while [ 1 ]
do
    break
done

rm -f $STATE_FIRST $STATE_SECOND
