#!/bin/bash

ARGS=4
zero=0

if [ "$#" -ne "$ARGS" ]
then
    echo "Usage: $(basename $0) [test] [good_out] [me_out] [buffer size in bytes]"
    exit 2
fi

file1="$1"
file2="$2"
file3="$3"
buf="$4"

test_count=$((RANDOM%50))
i=0

while [ "$i" -lt "$test_count" ]
do
    ./gen "$file1" "$file2" "$buf"
    ./midterm "$file1" "$buf" > "$file3"
    if ! diff "$file2" "$file3" 
    then
        echo "test #"$i" failed"
        exit 1
    else
        echo "test #"$i" done"
    fi
    let "i += 1"
done
rm -f "$file1" "$file2" "$file3"
