#!/bin/bash

out_file="$1"
buf="$2"
zero=0

declare -a Alphabet
Alphabet=(" " a b c d e f g h i j k l m n o p q r s t u v w x y z)
num_words=${#Alphabet[*]}

$(touch "$out_file")
chmod +w "$out_file"

exec 7>&1
exec > "$out_file"

lines=$((RANDOM%100))
while [ "$lines" -gt "$zero" ]
do
    length=$((RANDOM%$buf + RANDOM%($buf/2)))
    while [ "$length" -gt "$zero" ]
    do
        echo -n "${Alphabet[$((RANDOM%num_words))]}"
        let "length -= 1"
    done 
    echo ""
    let "lines -= 1"
done

exec 1>&7 7>&-
exit 0
